const FIG_LABELS = {
  prices:   { title: "MA vs V — price history",      desc: "Dual-axis price chart showing how closely the two stocks track each other." },
  beta:     { title: "Dynamic hedge ratio over time", desc: "The Kalman filter's real-time estimate of how many V shares offset one MA share." },
  zscore:   { title: "Spread z-score & trade signals", desc: "Entry (▲) and exit (▼) signals overlaid on the z-score. Dashed lines = thresholds." },
  equity:   { title: "Portfolio equity curve",        desc: "Portfolio value generated by matplotlib — matches the interactive chart above." },
  drawdown: { title: "Drawdown chart",               desc: "Peak-to-trough decline over time." },
  heatmap:  { title: "Monthly returns heatmap",      desc: "Each cell is one month's return. Green = profit, red = loss." },
};

function getFigLabel(name) {
  for (const [key, val] of Object.entries(FIG_LABELS)) {
    if (name.includes(key)) return val;
  }
  return { title: name.replace(/_/g, " "), desc: "" };
}

export default function DiagnosticsSection({ figures, base, filter, all, label, stepNum }) {
  if (!figures?.length) return null;

  const shown = all
    ? figures
    : figures.filter((f) => filter && f.name.includes(filter));

  if (!shown.length) return null;

  if (!all) {
    // Inline — no step wrapper
    return (
      <div style={{ marginBottom: 8 }}>
        {label && <p style={{ fontSize: 13, color: "var(--text-muted)", marginBottom: 12 }}>{label}</p>}
        <div className="figure-grid" style={{ gridTemplateColumns: "1fr" }}>
          {shown.map((f) => {
            const meta = getFigLabel(f.name);
            return (
              <div className="figure-card" key={f.name}>
                <img src={`${base}${f.file}`} alt={meta.title} loading="lazy" />
                <div className="figure-cap">{meta.desc}</div>
              </div>
            );
          })}
        </div>
      </div>
    );
  }

  return (
    <section className="step">
      {stepNum && <div className="step-number">{stepNum}</div>}
      <h2 className="step-heading">{label || "Diagnostic charts"}</h2>
      <p className="step-body">
        Charts generated by the Python engine. These are the exact plots a quant would
        use to sanity-check the strategy before trading it live.
      </p>
      <div className="figure-grid">
        {shown.map((f) => {
          const meta = getFigLabel(f.name);
          return (
            <div className="figure-card" key={f.name}>
              <img src={`${base}${f.file}`} alt={meta.title} loading="lazy" />
              <div className="figure-cap">
                <strong style={{ color: "var(--text)", display: "block", marginBottom: 4 }}>{meta.title}</strong>
                {meta.desc}
              </div>
            </div>
          );
        })}
      </div>
    </section>
  );
}
